import './index.css';
import styles from './layout.module.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Logo } from './components/logo/logo';
import { Button } from './components/button/button';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header className={styles.header}>
          <Logo />
          <nav className={styles.nav}>
            <ul className={styles.nav_list}>
              <li className={styles.nav_item}>
                <Link href={'/'} className={styles.nav_link}>
                  Уроки
                </Link>
              </li>
              <li className={styles.nav_item}>
                <Link href={'/'} className={styles.nav_link}>
                  Галерея
                </Link>
              </li>
              <li className={styles.nav_item}>
                <Link href={'/'} className={styles.nav_link}>
                  Блог
                </Link>
              </li>
            </ul>
            <ul className={styles.button_list}>
              <li>
                <Button>
                  Зарегистрироваться
                </Button>
              </li>
              <li>
                <Button styleType='secondary'>
                  Войти
                </Button>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
